<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4da2ed6b-9628-45e2-8b14-5a1674b4de89</UserSecretsId>
    <RunAOTCompilation>false</RunAOTCompilation>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\PlaceOfInterest.GoogleMaps\PlaceOfInterest.GoogleMaps.csproj" />
  </ItemGroup>

</Project>
